name: Glados CD

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

env:
  tar: "glados.tar.gz"

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Stack
        run: curl -sSL https://get.haskellstack.org/ | sh -s - -d /opt/stack/bin

      - name: Build with Stack
        run: |
          make artifact

      - name: Set Artifact version
        id: tag
        run: |
          package_version="$(awk '/^version:/{print $2}' package.yaml)"
          echo "Release version $package_version"
          echo "PACKAGE_VERSION=$package_version" >> $GITHUB_ENV

      - name: Move and rename file
        run: mv ${{ env.tar }} "glados-v${{ env.PACKAGE_VERSION }}.tar.gz"
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.PACKAGE_VERSION }}
          artifacts: "glados-v${{ env.PACKAGE_VERSION }}.tar.gz"
          allowUpdates: true
          # skipIfReleaseExists: true
          token: ${{ github.token }}
          replacesArtifacts: true
