name: Glados CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  EXECUTABLES: "Glados"

jobs:
  check_repository_is_clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Check for .stack-work directory
        run: |
          if [ -d .stack-work ]; then
            echo "::error::Found .stack-work directory. Please remove it."
            exit 1
          else
            echo "No .stack-work directory found."
          fi

  build-project:
    runs-on: ubuntu-latest
    needs: [check_repository_is_clean]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install libgmp
        run: |
          sudo apt-get update
          sudo apt-get install libgmp10-dev -y

      - name: Install haskell and stack
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-version: "2.13.1"
          ghc-version: "9.4.8"

      - name: Setup stack
        run: stack setup
      - name: Build project
        run: |
          make
          make unit_tests > test_output.txt 2>&1

      - name: Check test results
        run: |
          grep "Cases" test_output.txt | awk '
          /Failures: 0/ { passed = 1 }
          /Failures: [^0]/ { failed = 1 }
          END {
              if (failed) {
                  print "Some tests failed"
                  exit 1
              } else if (passed) {
                  print "All tests passed"
              }
          }'

      - name: Check executables
        run: |
          filename="${EXECUTABLES}"
          IFS=','
          read -ra ADDR <<< "$filename"
          for i in "${ADDR[@]}"
          do
          [[ ! -f "$i" || ! -x "$i" ]] && echo "::error::$i is missing or not a executable." && exit 1
          done
          exit 0
