name: Glados CD

on:
  workflow_run:
    workflows: ["Glados CI", "Check Release Existence"]
    branches: [main]
    types:
      - completed

permissions:
  contents: write
  packages: write

env:
  tar: "glados.tar.gz"

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install libgmp
        run: |
          sudo apt-get update
          sudo apt-get install libgmp10-dev -y

      - name: Install haskell and stack
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-version: "2.13.1"
          ghc-version: "9.4.8"

      - name: Build release
        run: |
          make artifact

      - name: Set Artifact version
        id: tag
        run: |
          package_version="$(awk '/^version:/{print $2}' package.yaml)"
          echo "Release version $package_version"
          echo "PACKAGE_VERSION=$package_version" >> $GITHUB_ENV

      # - name: Move and rename file
      #   run: mv ${{ env.tar }} "glados-v${{ env.PACKAGE_VERSION }}.tar.gz"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.PACKAGE_VERSION }}
          artifacts: "glados.tar.gz"
          artifactContentType: "application/gzip"
          allowUpdates: true
          token: ${{ github.token }}
          replacesArtifacts: true
          bodyFile: "CHANGELOG.md"
          skipIfReleaseExists: true
