name: Glados CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  EXECUTABLES: "Glados"

jobs:
  check_repository_is_clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Check for .stack-work directory
        run: |
          if [ -d .stack-work ]; then
            echo "::error::Found .stack-work directory. Please remove it."
            exit 1
          else
            echo "No .stack-work directory found."
          fi

  build-project:
    runs-on: ubuntu-latest
    needs: [check_repository_is_clean]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
